{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.share",
    "module": "share_plus_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-8cd19e509d6bece8ccd74aef027c4ca947363095"
          }
        }
      ],
      "files": [
        {
          "name": "share_plus_profile-1.0.aar",
          "url": "share_plus_profile-1.0.aar",
          "size": 19345,
          "sha512": "52877c6413e4dc0dfd5b2a7518a31366a16e5b6ca596dbf86ac1a6ffcd984ad88b1169fb3e3b4cdf9585fea7e3e0ef1bbe0610bbf588cbb23ce9396153e52927",
          "sha256": "72e8c1c1ade74a08cb72160b7ba226141b4b159db5a204c4c3e3925731019a08",
          "sha1": "ad498b67a9fd1667dbf931185f7661c27629f2e0",
          "md5": "c956f0d23f25eaddf922b597f6cb70de"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-8cd19e509d6bece8ccd74aef027c4ca947363095"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.2"
          }
        }
      ],
      "files": [
        {
          "name": "share_plus_profile-1.0.aar",
          "url": "share_plus_profile-1.0.aar",
          "size": 19345,
          "sha512": "52877c6413e4dc0dfd5b2a7518a31366a16e5b6ca596dbf86ac1a6ffcd984ad88b1169fb3e3b4cdf9585fea7e3e0ef1bbe0610bbf588cbb23ce9396153e52927",
          "sha256": "72e8c1c1ade74a08cb72160b7ba226141b4b159db5a204c4c3e3925731019a08",
          "sha1": "ad498b67a9fd1667dbf931185f7661c27629f2e0",
          "md5": "c956f0d23f25eaddf922b597f6cb70de"
        }
      ]
    },
    {
      "name": "profileVariantProfileSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "share_plus_profile-1.0-sources.jar",
          "url": "share_plus_profile-1.0-sources.jar",
          "size": 7530,
          "sha512": "8fd42cb0575b98870f490bead8dd67fa672dc8562fc8e375e3e959d6c3428303ddf5bea3a56ec2ca61137ef1688ce1daf9700a38f2883e9fc1533a4f9f0341f4",
          "sha256": "4fc6ff44f1642ab025c792c24e412319c906950037bb2333fa3c9eaaa2214d90",
          "sha1": "72c0dfc83614bcf0785cae4c0c82fc5590688e3f",
          "md5": "8b03d5bdeab548ecd0a44f80b96e8538"
        }
      ]
    },
    {
      "name": "profileVariantProfileJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "share_plus_profile-1.0-javadoc.jar",
          "url": "share_plus_profile-1.0-javadoc.jar",
          "size": 283806,
          "sha512": "b108e72ab81c888c4c78aa4e939fec5fee1ff36811208b8edb562e239031762d828731cc9d316027a627cb9be84b5d7ab2d9860de0c6f1be5a2924cdf640821b",
          "sha256": "82b5db2c2660203aedb255092839e432b0fcb5cdb4d348d96729d84c6a5a137f",
          "sha1": "14ab15ec8d4fd7c9b3ca316c3c518e2f5fbf84a1",
          "md5": "345847a7db2dd068de1d9763415302dd"
        }
      ]
    }
  ]
}
