{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.camerax",
    "module": "camera_android_camerax_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-8cd19e509d6bece8ccd74aef027c4ca947363095"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "camera_android_camerax_profile-1.0.aar",
          "url": "camera_android_camerax_profile-1.0.aar",
          "size": 559124,
          "sha512": "401f863125868867fdb818012927eda870aeeb4962d2b1799ca05397c025c309b1e641c10d0bdfcc788df0647f5cfcbe505af725820bb481aeea4410e9e0b3e4",
          "sha256": "311c2d883c5a929fe1d6fe36349116021c2a8b9e40d87cc93c7ec1db3adfbf19",
          "sha1": "97dfedb7c72e708c5a3e170dbaeecf84dc2a5767",
          "md5": "45415fd55b75d59670046cb0059e5cc5"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-8cd19e509d6bece8ccd74aef027c4ca947363095"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.5.0-beta01"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.5.0-beta01"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.5.0-beta01"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.5.0-beta01"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.4.0-android"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "camera_android_camerax_profile-1.0.aar",
          "url": "camera_android_camerax_profile-1.0.aar",
          "size": 559124,
          "sha512": "401f863125868867fdb818012927eda870aeeb4962d2b1799ca05397c025c309b1e641c10d0bdfcc788df0647f5cfcbe505af725820bb481aeea4410e9e0b3e4",
          "sha256": "311c2d883c5a929fe1d6fe36349116021c2a8b9e40d87cc93c7ec1db3adfbf19",
          "sha1": "97dfedb7c72e708c5a3e170dbaeecf84dc2a5767",
          "md5": "45415fd55b75d59670046cb0059e5cc5"
        }
      ]
    },
    {
      "name": "profileVariantProfileSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "camera_android_camerax_profile-1.0-sources.jar",
          "url": "camera_android_camerax_profile-1.0-sources.jar",
          "size": 87945,
          "sha512": "a7a881deae4f1e79d1bd49fe7c5cc49c2e4cf81e5d22526f52a0afd15982cd85c07fc61526f2f4a4454a3c384a62194ce025d04c1e2b0e039e7c023930842bd1",
          "sha256": "399eacab88b0cd6d68f90f097d17b9a8951bb97dea88d08779bf2a8080960c1f",
          "sha1": "a7a1ac137bac6d932018f4053a0e035405cde4c5",
          "md5": "7fda4ccfd270abb898a3fbec07f2fc5d"
        }
      ]
    },
    {
      "name": "profileVariantProfileJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "camera_android_camerax_profile-1.0-javadoc.jar",
          "url": "camera_android_camerax_profile-1.0-javadoc.jar",
          "size": 1100225,
          "sha512": "b3a627a7a7aa2bbaf55c95401b4a28ad1eed137fb2b4ac96bf4ed94868d82bf36c52aca2000b3a4c953fc75c70584f67f810c97451bb72029723693b1d875b32",
          "sha256": "0869a868c0586855ca510d2c7772061baa6083618e664979e334405750cf3da5",
          "sha1": "07a18108ffd53cb47a2da5a9c4cd427869c38973",
          "md5": "db1d6222b29832809dea364debe5bdf9"
        }
      ]
    }
  ]
}
