{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.share",
    "module": "share_plus_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-8cd19e509d6bece8ccd74aef027c4ca947363095"
          }
        }
      ],
      "files": [
        {
          "name": "share_plus_debug-1.0.aar",
          "url": "share_plus_debug-1.0.aar",
          "size": 19341,
          "sha512": "60a71dce19e19289132e3850fefb42f35435d5e682cc91366246a0c9df65fa36166a62d2a74b22873bde656aa64d872f00fbeb4ab39b9b120dc86aef5932eb0c",
          "sha256": "7537822629175e96abebf0a1d4f3bb959a33277aa5889cdde1a9103ba02a67f7",
          "sha1": "7bddc35348da41f66e5991242ba4365de4bddd3d",
          "md5": "303c8be1f91dbc7af6e7133529026a80"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-8cd19e509d6bece8ccd74aef027c4ca947363095"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.2"
          }
        }
      ],
      "files": [
        {
          "name": "share_plus_debug-1.0.aar",
          "url": "share_plus_debug-1.0.aar",
          "size": 19341,
          "sha512": "60a71dce19e19289132e3850fefb42f35435d5e682cc91366246a0c9df65fa36166a62d2a74b22873bde656aa64d872f00fbeb4ab39b9b120dc86aef5932eb0c",
          "sha256": "7537822629175e96abebf0a1d4f3bb959a33277aa5889cdde1a9103ba02a67f7",
          "sha1": "7bddc35348da41f66e5991242ba4365de4bddd3d",
          "md5": "303c8be1f91dbc7af6e7133529026a80"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "share_plus_debug-1.0-sources.jar",
          "url": "share_plus_debug-1.0-sources.jar",
          "size": 7530,
          "sha512": "8fd42cb0575b98870f490bead8dd67fa672dc8562fc8e375e3e959d6c3428303ddf5bea3a56ec2ca61137ef1688ce1daf9700a38f2883e9fc1533a4f9f0341f4",
          "sha256": "4fc6ff44f1642ab025c792c24e412319c906950037bb2333fa3c9eaaa2214d90",
          "sha1": "72c0dfc83614bcf0785cae4c0c82fc5590688e3f",
          "md5": "8b03d5bdeab548ecd0a44f80b96e8538"
        }
      ]
    },
    {
      "name": "debugVariantDebugJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "share_plus_debug-1.0-javadoc.jar",
          "url": "share_plus_debug-1.0-javadoc.jar",
          "size": 283806,
          "sha512": "b108e72ab81c888c4c78aa4e939fec5fee1ff36811208b8edb562e239031762d828731cc9d316027a627cb9be84b5d7ab2d9860de0c6f1be5a2924cdf640821b",
          "sha256": "82b5db2c2660203aedb255092839e432b0fcb5cdb4d348d96729d84c6a5a137f",
          "sha1": "14ab15ec8d4fd7c9b3ca316c3c518e2f5fbf84a1",
          "md5": "345847a7db2dd068de1d9763415302dd"
        }
      ]
    }
  ]
}
