{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.camerax",
    "module": "camera_android_camerax_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-8cd19e509d6bece8ccd74aef027c4ca947363095"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "camera_android_camerax_release-1.0.aar",
          "url": "camera_android_camerax_release-1.0.aar",
          "size": 531059,
          "sha512": "1355f9a344caf5916a5f24abbf9d841d88f79ebbd8d1620e58021ce3f581df3d22cb81a55ef9e6fadd05a54cc4fec99c3deb22c98e28a8c8fb4de8a1f8ccea48",
          "sha256": "b2f49692cc5a2d1471d25b2c141e1625b5b0a224cc812f019461a3f0cb4fdf96",
          "sha1": "fee4a3bd4243dd38e4c52730b73172609ddd5759",
          "md5": "5af7b310334cfacecba31a365035c018"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-8cd19e509d6bece8ccd74aef027c4ca947363095"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.5.0-beta01"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.5.0-beta01"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.5.0-beta01"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.5.0-beta01"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.4.0-android"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "camera_android_camerax_release-1.0.aar",
          "url": "camera_android_camerax_release-1.0.aar",
          "size": 531059,
          "sha512": "1355f9a344caf5916a5f24abbf9d841d88f79ebbd8d1620e58021ce3f581df3d22cb81a55ef9e6fadd05a54cc4fec99c3deb22c98e28a8c8fb4de8a1f8ccea48",
          "sha256": "b2f49692cc5a2d1471d25b2c141e1625b5b0a224cc812f019461a3f0cb4fdf96",
          "sha1": "fee4a3bd4243dd38e4c52730b73172609ddd5759",
          "md5": "5af7b310334cfacecba31a365035c018"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "camera_android_camerax_release-1.0-sources.jar",
          "url": "camera_android_camerax_release-1.0-sources.jar",
          "size": 87945,
          "sha512": "a7a881deae4f1e79d1bd49fe7c5cc49c2e4cf81e5d22526f52a0afd15982cd85c07fc61526f2f4a4454a3c384a62194ce025d04c1e2b0e039e7c023930842bd1",
          "sha256": "399eacab88b0cd6d68f90f097d17b9a8951bb97dea88d08779bf2a8080960c1f",
          "sha1": "a7a1ac137bac6d932018f4053a0e035405cde4c5",
          "md5": "7fda4ccfd270abb898a3fbec07f2fc5d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "camera_android_camerax_release-1.0-javadoc.jar",
          "url": "camera_android_camerax_release-1.0-javadoc.jar",
          "size": 1098307,
          "sha512": "9d572e14b31049646de0572a2901724e6341a7a6b3d35f099bca8d8a5ea93a907f7792345cbebb6c906c4f5a8a4306c1c9f609fb2b16f00ec5af9dfa04c509fb",
          "sha256": "30d538a5959c9a5b99ba1d0b727e4b9579c4a8cbb0a08b593b39866faaf4b1dc",
          "sha1": "2bbe3331a8a2c5d903c4b81737775a2ce8db0e9a",
          "md5": "081289bc233d0195672707c36f09012a"
        }
      ]
    }
  ]
}
