{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.androidintent",
    "module": "android_intent_plus_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-8cd19e509d6bece8ccd74aef027c4ca947363095"
          }
        }
      ],
      "files": [
        {
          "name": "android_intent_plus_debug-1.0.aar",
          "url": "android_intent_plus_debug-1.0.aar",
          "size": 10198,
          "sha512": "02ba7031376ad1e27ecd1203c86428400cda30d9ec16db6387ebc18aa89071a46e8f7005893866a2a09cb2444b37e726934d34715067ae10d075195743fbfda8",
          "sha256": "052a52efff71c49b68278696610f1777ebd2b8aadeecc7ad891c7b753f866b2e",
          "sha1": "143df684e1edd6b3233e6f768f24c3c349f5fc03",
          "md5": "785c23329a6d79c3a2c923118db02277"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-8cd19e509d6bece8ccd74aef027c4ca947363095"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.2"
          }
        }
      ],
      "files": [
        {
          "name": "android_intent_plus_debug-1.0.aar",
          "url": "android_intent_plus_debug-1.0.aar",
          "size": 10198,
          "sha512": "02ba7031376ad1e27ecd1203c86428400cda30d9ec16db6387ebc18aa89071a46e8f7005893866a2a09cb2444b37e726934d34715067ae10d075195743fbfda8",
          "sha256": "052a52efff71c49b68278696610f1777ebd2b8aadeecc7ad891c7b753f866b2e",
          "sha1": "143df684e1edd6b3233e6f768f24c3c349f5fc03",
          "md5": "785c23329a6d79c3a2c923118db02277"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android_intent_plus_debug-1.0-sources.jar",
          "url": "android_intent_plus_debug-1.0-sources.jar",
          "size": 6335,
          "sha512": "b30bb2280bb0d3960fc45d340dde9515b060a992160783ca253f9a7da3787048edad37a1c44f5f34826872e1ceb64b84261ab643a75d5af659d71df80ec508ba",
          "sha256": "e2a7de31eef1b6501f37d46e602aa1e1d98d31ff4e951cbaf62d314962a10d3c",
          "sha1": "67f83b5baf16ad3fdd13055b3e4480c95c972102",
          "md5": "3d55fe9ec7d9c45004caa2285168b1a1"
        }
      ]
    },
    {
      "name": "debugVariantDebugJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android_intent_plus_debug-1.0-javadoc.jar",
          "url": "android_intent_plus_debug-1.0-javadoc.jar",
          "size": 278173,
          "sha512": "ad8bc01380873b1b80860cc0afa099405faa160bdb2645729e46871f5f666316e0221e5c26ff10bea62f6e92688288017dd48ae2e2ed418dfd63e84995068efa",
          "sha256": "305634a918e74ddbecb74f9bbab67408a74e6d6e9c69fb150f6c1d6c8b03fd8c",
          "sha1": "bfbb160a5334bfd994a10fa05b328be03e9d9098",
          "md5": "1208725680815b3ee693530dee86054d"
        }
      ]
    }
  ]
}
