{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.launchexternalapp",
    "module": "external_app_launcher_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-8cd19e509d6bece8ccd74aef027c4ca947363095"
          }
        }
      ],
      "files": [
        {
          "name": "external_app_launcher_debug-1.0.aar",
          "url": "external_app_launcher_debug-1.0.aar",
          "size": 3442,
          "sha512": "d67b62fa268ce6b4bc4223d390d9ca15004dbabaaf744eef1edc69ddfe82923a78ad7245dfd2015ea68576628c1d683144e38edaf35a75be2abbab441a07835d",
          "sha256": "1d4a04fdf9ff5e1b6a3a4da636b00a8213e69f371fbfcb9c2c6a81d2579f809d",
          "sha1": "7c4c6af5d52e8e77d9072e84ebdecc8a35b91f31",
          "md5": "2ee8ac05fe3797288f9a0b3776d11b99"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-8cd19e509d6bece8ccd74aef027c4ca947363095"
          }
        }
      ],
      "files": [
        {
          "name": "external_app_launcher_debug-1.0.aar",
          "url": "external_app_launcher_debug-1.0.aar",
          "size": 3442,
          "sha512": "d67b62fa268ce6b4bc4223d390d9ca15004dbabaaf744eef1edc69ddfe82923a78ad7245dfd2015ea68576628c1d683144e38edaf35a75be2abbab441a07835d",
          "sha256": "1d4a04fdf9ff5e1b6a3a4da636b00a8213e69f371fbfcb9c2c6a81d2579f809d",
          "sha1": "7c4c6af5d52e8e77d9072e84ebdecc8a35b91f31",
          "md5": "2ee8ac05fe3797288f9a0b3776d11b99"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "external_app_launcher_debug-1.0-sources.jar",
          "url": "external_app_launcher_debug-1.0-sources.jar",
          "size": 1839,
          "sha512": "572ebafca55aa43f43562e112518fb112a1051dcda2fa47fd85e86b68efc9463aa24f776d1311f9fc5641f633bb576d70fdf1d331f4968ea9a86642f5451b6af",
          "sha256": "a13f19f5879784db3ad0ad5e37b7b748c7eb08fc43125d476e26c7b8db45648b",
          "sha1": "62e2b9b540d03faba1173d07939fa7564105f299",
          "md5": "988831cb67d3ac2ebc7e348444367d61"
        }
      ]
    },
    {
      "name": "debugVariantDebugJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "external_app_launcher_debug-1.0-javadoc.jar",
          "url": "external_app_launcher_debug-1.0-javadoc.jar",
          "size": 262196,
          "sha512": "7a4b0d408331fe29a7ad515a48fba21f8ddeb801e220c1aa898d48c5181628a8c80360d45162c709d0c3b3019a6bc31a704cae7d7767014e893a79578769f1bb",
          "sha256": "193912d7595052b00f2fc337ffb58132d242328f1fc8cb07003da34d9d60bad6",
          "sha1": "ba4d5e5af272f1d8b0b0210063c7860d9d52d3c6",
          "md5": "3f89e1804f97e9a3b2e787f544f4ddb7"
        }
      ]
    }
  ]
}
