{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pichillilorenzo.flutter_inappwebview_android",
    "module": "flutter_inappwebview_android_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-8cd19e509d6bece8ccd74aef027c4ca947363095"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_inappwebview_android_profile-1.0.aar",
          "url": "flutter_inappwebview_android_profile-1.0.aar",
          "size": 542619,
          "sha512": "d1ef07282e6a3844f065c454e43eb3a9565a5d7eb727a836bc95e60c7984c8df2b644ca2d71b8dd552b4ebf75d5d7f7de60a2baebe9293a612ab73c9bef39a9e",
          "sha256": "dd10c8ab7637ae0aa8c8f81cc9126482e8912ffe9f886138e77c60981e329150",
          "sha1": "ad9d2d437624fbb5242fc876eb29444d1a8cbd72",
          "md5": "8f0566183d7a184c5f5e6e11c40dd498"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-8cd19e509d6bece8ccd74aef027c4ca947363095"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_inappwebview_android_profile-1.0.aar",
          "url": "flutter_inappwebview_android_profile-1.0.aar",
          "size": 542619,
          "sha512": "d1ef07282e6a3844f065c454e43eb3a9565a5d7eb727a836bc95e60c7984c8df2b644ca2d71b8dd552b4ebf75d5d7f7de60a2baebe9293a612ab73c9bef39a9e",
          "sha256": "dd10c8ab7637ae0aa8c8f81cc9126482e8912ffe9f886138e77c60981e329150",
          "sha1": "ad9d2d437624fbb5242fc876eb29444d1a8cbd72",
          "md5": "8f0566183d7a184c5f5e6e11c40dd498"
        }
      ]
    },
    {
      "name": "profileVariantProfileSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_inappwebview_android_profile-1.0-sources.jar",
          "url": "flutter_inappwebview_android_profile-1.0-sources.jar",
          "size": 231367,
          "sha512": "724dc195bfbe4b28d89808344871daa160afad873ef68cf45446c7367b99b3bef629039bef0c408ae62bce6321f437f389b09520366a50be43d8a6628dbee098",
          "sha256": "516e4f125d631258bc8b2fcddcbe2cc80259886899125edb9cb7bb536d2d0603",
          "sha1": "a1de5e80df1e9c9ddbb81872d908bc2abb82ddde",
          "md5": "8d71034285687670dcf185251ed6d329"
        }
      ]
    },
    {
      "name": "profileVariantProfileJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_inappwebview_android_profile-1.0-javadoc.jar",
          "url": "flutter_inappwebview_android_profile-1.0-javadoc.jar",
          "size": 1167524,
          "sha512": "e92546ef24b030f163869ca5b52ccd018ee4f9074d72f0de05b342454f39333f2bc679e9276380af162b20f70e5f8b273833609f137b7262548f19cbfcff0187",
          "sha256": "ac5983613dea069ba9f0781b3b3a1e576fb81a2e803247054b1f6256a0ecd651",
          "sha1": "22125174c4ffbf56deebbaa92498c1a16919c33c",
          "md5": "d0cad60e464417ba8e1f32f7857c813d"
        }
      ]
    }
  ]
}
