{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.androidintent",
    "module": "android_intent_plus_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-8cd19e509d6bece8ccd74aef027c4ca947363095"
          }
        }
      ],
      "files": [
        {
          "name": "android_intent_plus_release-1.0.aar",
          "url": "android_intent_plus_release-1.0.aar",
          "size": 9722,
          "sha512": "206226b14e090c2574b77cef5c9fb9be5d636ca5d5d100d890abf2a4294cbeeee98bb8dbc053e1ef806cac83e75cd18cd3352c48174bd670b5324e2d5a1a42f8",
          "sha256": "cb2aaa9cb1691129d4cf68e9237314bd444504c0f275c4bc3f0ee2f44788766e",
          "sha1": "86d6a6b2b9e160139ae0c1064da7495259b6d080",
          "md5": "921f92fd6ba05fc1aa49a15352259a2c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-8cd19e509d6bece8ccd74aef027c4ca947363095"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.2"
          }
        }
      ],
      "files": [
        {
          "name": "android_intent_plus_release-1.0.aar",
          "url": "android_intent_plus_release-1.0.aar",
          "size": 9722,
          "sha512": "206226b14e090c2574b77cef5c9fb9be5d636ca5d5d100d890abf2a4294cbeeee98bb8dbc053e1ef806cac83e75cd18cd3352c48174bd670b5324e2d5a1a42f8",
          "sha256": "cb2aaa9cb1691129d4cf68e9237314bd444504c0f275c4bc3f0ee2f44788766e",
          "sha1": "86d6a6b2b9e160139ae0c1064da7495259b6d080",
          "md5": "921f92fd6ba05fc1aa49a15352259a2c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android_intent_plus_release-1.0-sources.jar",
          "url": "android_intent_plus_release-1.0-sources.jar",
          "size": 6335,
          "sha512": "b30bb2280bb0d3960fc45d340dde9515b060a992160783ca253f9a7da3787048edad37a1c44f5f34826872e1ceb64b84261ab643a75d5af659d71df80ec508ba",
          "sha256": "e2a7de31eef1b6501f37d46e602aa1e1d98d31ff4e951cbaf62d314962a10d3c",
          "sha1": "67f83b5baf16ad3fdd13055b3e4480c95c972102",
          "md5": "3d55fe9ec7d9c45004caa2285168b1a1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android_intent_plus_release-1.0-javadoc.jar",
          "url": "android_intent_plus_release-1.0-javadoc.jar",
          "size": 278173,
          "sha512": "ad8bc01380873b1b80860cc0afa099405faa160bdb2645729e46871f5f666316e0221e5c26ff10bea62f6e92688288017dd48ae2e2ed418dfd63e84995068efa",
          "sha256": "305634a918e74ddbecb74f9bbab67408a74e6d6e9c69fb150f6c1d6c8b03fd8c",
          "sha1": "bfbb160a5334bfd994a10fa05b328be03e9d9098",
          "md5": "1208725680815b3ee693530dee86054d"
        }
      ]
    }
  ]
}
