{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.urllauncher",
    "module": "url_launcher_android_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-8cd19e509d6bece8ccd74aef027c4ca947363095"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_profile-1.0.aar",
          "url": "url_launcher_android_profile-1.0.aar",
          "size": 23570,
          "sha512": "961a6dc4d5f54ae084d228da11838b9afbb515cca5bef12f18d33d7bbdaa4581aefd81bc836a18aa9e94c0a8baad8853069037b41215580472de7d8ee3764b4e",
          "sha256": "c9fbd3b3a98d6538077bbcb6aafe2ce3f1c4081298a6bd9a3a79c3c73f740866",
          "sha1": "58a28c4e632875f338fa184701e35c512e8cafa5",
          "md5": "d85fbbba82b0f024ac2f7d6e48ee12e5"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-8cd19e509d6bece8ccd74aef027c4ca947363095"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_profile-1.0.aar",
          "url": "url_launcher_android_profile-1.0.aar",
          "size": 23570,
          "sha512": "961a6dc4d5f54ae084d228da11838b9afbb515cca5bef12f18d33d7bbdaa4581aefd81bc836a18aa9e94c0a8baad8853069037b41215580472de7d8ee3764b4e",
          "sha256": "c9fbd3b3a98d6538077bbcb6aafe2ce3f1c4081298a6bd9a3a79c3c73f740866",
          "sha1": "58a28c4e632875f338fa184701e35c512e8cafa5",
          "md5": "d85fbbba82b0f024ac2f7d6e48ee12e5"
        }
      ]
    },
    {
      "name": "profileVariantProfileSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "url_launcher_android_profile-1.0-sources.jar",
          "url": "url_launcher_android_profile-1.0-sources.jar",
          "size": 9313,
          "sha512": "992d095df67d1b653b20de471d38ae483e298811f5bb470cad4d7ffabf553451e168e5d3ac4a9593280f6983d74eb27dfafd8ced6d70da574dc2e5648944693c",
          "sha256": "1fe028244b497b0578b3df86209499fe63afee2bba459df71d15f0cc0f3f149c",
          "sha1": "888b3d3e9e6424ca726c49ce44266330d9a165c5",
          "md5": "1e4a34aa65b526add66b2064c8175c7e"
        }
      ]
    },
    {
      "name": "profileVariantProfileJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "url_launcher_android_profile-1.0-javadoc.jar",
          "url": "url_launcher_android_profile-1.0-javadoc.jar",
          "size": 332691,
          "sha512": "a9ff208d2bef4f43e21eb10c5f0e8d3b0481f30d649b8005db5e77dd5311fcfdb140d681aa09c8eb50473e26f9d399b8f839b624bc1c05f19204d877c6f4c173",
          "sha256": "63b07f81f2bad34f82845c305d7bc1a6af2dcf44f3d4cb536015e1425db74ab9",
          "sha1": "03563fd52593cec899acfda660c47abab6cad07d",
          "md5": "b43b6972ed2339fa6f6b3d6dbb07feba"
        }
      ]
    }
  ]
}
